"""change isbn to string

Revision ID: 5c582fdaf3ae
Revises: 111022cc1728
Create Date: 2026-05-15 10:36:39.523067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c582fdaf3ae'
down_revision: Union[str, Sequence[str], None] = '111022cc1728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.alter_column('book', 'isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)
    op.create_table('customer',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
